server:
  port: 8001



spring:
  application:
    name: demo-spring-krest-job
  profiles:
    active: dev


# 配置服务的基本信息
krest:
  job:
    # 服务注册中心ip与port
    admin_address: http://localhost:9001
    # 本机的 app 信息
    weight: 1
    client_app_name: ${spring.application.name}
    client_address: http://localhost:8001