server:
  port: 8002



spring:
  application:
    name: demo-spring-krest-job
  profiles:
    active: dev


# 配置服务的基本信息
krest:
  job:
    # 服务注册中心ip与port
    admin_address: http://localHost:9001
    weight: 0.7
    # 本机的 app 信息
    client_app_name: ${spring.application.name}
    client_address: http://localHost:8002